services:
  postgres:
    container_name: postgres-sql-1
    image: postgres
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: mohamed
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres: